using System;
using System.Collections.Generic;
using Godot;
using MemoryPack;

namespace Game;

[MemoryPackable]
public partial class GameData
{
    // Add game-related save data here
    public int CurrentHealth { get; set; } = 100;

    // Generated by Copilot: track how many burgers the player has eaten
    public int BurgersEaten { get; set; } = 0;

    // Generated by GitHub Copilot: List of collected keys (identified by their node name)
    public HashSet<string> CollectedKeys { get; set; } = [];

    // Generated by Copilot: The ID of the single statue the player is currently carrying.
    public string? HeldStatueId { get; set; } = null;

    // Generated by Copilot: Tracks which statues have been placed correctly.
    public Dictionary<string, bool> StatuePlaced { get; set; } = new Dictionary<string, bool>();

    public ulong TimeGameStarted { get; set; }

    /// <summary> Spendable battlefield currency (Burger Bucks). </summary>
    public int Currency { get; set; } = 80;

    /// <summary> Current round (1-based). Income is granted at round end, then this advances. </summary>
    public int CurrentRound { get; set; } = 1;

    /// <summary> Base income when a round ends (before per-round scaling). </summary>
    public int BasePerRoundIncome { get; set; } = 100;

    /// <summary> Added to income each round after the first: income += (CurrentRound - 1) * this. </summary>
    public int PerRoundIncomeDelta { get; set; } = 20;

    public GameData()
    {
        TimeGameStarted = Time.GetTicksMsec();
    }

    /// <summary> Income granted for completing the current round (before CurrentRound is advanced). </summary>
    public int ComputeRoundEndIncome()
    {
        return BasePerRoundIncome + (CurrentRound - 1) * PerRoundIncomeDelta;
    }

    public bool TrySpend(int amount)
    {
        if (amount <= 0)
            return true;
        if (Currency < amount)
            return false;
        Currency -= amount;
        return true;
    }

    public void GrantCurrency(int amount)
    {
        if (amount <= 0)
            return;
        Currency += amount;
    }

    /// <summary> Call when a round ends: grant income for the completed round, then advance round index. </summary>
    public void ApplyRoundEndIncomeAndAdvance()
    {
        GrantCurrency(ComputeRoundEndIncome());
        CurrentRound += 1;
    }

    // public int FinalKilled { get; set; } = 0;

    // [MemoryPackIgnore]
    // public Action? FinalThingy { get; set; }
}
