using System;
using System.Collections.Generic;
using Godot;
using MemoryPack;

namespace Game;

[MemoryPackable]
public partial class GameData
{
    // Add game-related save data here
    public int CurrentHealth { get; set; } = 100;

    // Generated by Copilot: track how many burgers the player has eaten
    public int BurgersEaten { get; set; } = 0;

    // Generated by GitHub Copilot: List of collected keys (identified by their node name)
    public HashSet<string> CollectedKeys { get; set; } = [];

    // Generated by Copilot: The ID of the single statue the player is currently carrying.
    public string? HeldStatueId { get; set; } = null;

    // Generated by Copilot: Tracks which statues have been placed correctly.
    public Dictionary<string, bool> StatuePlaced { get; set; } = new Dictionary<string, bool>();

    public ulong TimeGameStarted { get; set; }

    public GameData()
    {
        TimeGameStarted = Time.GetTicksMsec();
    }

    // public int FinalKilled { get; set; } = 0;

    // [MemoryPackIgnore]
    // public Action? FinalThingy { get; set; }
}
