using System;
using Godot;

namespace Game.Entities;

public partial class Door : Node3D
{
    [Export]
    public string RequiredKeyName { get; set; } = "gold_key"; // Generated by Copilot: the inventory key id required to open

    [Export]
    public NodePath DoorBodyPath { get; set; } = "StaticBody3D";

    [Export]
    public NodePath TriggerAreaPath { get; set; } = "Area3D";

    [Export]
    public NodePath AnimationPlayerPath { get; set; } = "AnimationPlayer";

    [Export]
    public NodePath OpenEffectPath { get; set; } = "AudioStreamPlayer";

    private bool opened = false;
    private StaticBody3D? doorBody;
    private Area3D? triggerArea;
    private AnimationPlayer? animationPlayer;
    private AudioStreamPlayer? openEffect;

    public override void _Ready()
    {
        // Generated by Copilot: wire up nodes from exported paths
        doorBody = GetNodeOrNull<StaticBody3D>(DoorBodyPath);
        triggerArea = GetNodeOrNull<Area3D>(TriggerAreaPath);
        animationPlayer = GetNodeOrNull<AnimationPlayer>(AnimationPlayerPath);
        openEffect = GetNodeOrNull<AudioStreamPlayer>(OpenEffectPath);

        if (triggerArea != null)
            triggerArea.BodyEntered += OnBodyEntered;
    }

    private void OnBodyEntered(Node body)
    {
        // Generated by Copilot: require player type and key in inventory
        if (body is Farmer)
        {
            if (opened)
            {
                return;
            }

            var inventory = Game.Manager.Instance.Data.CollectedKeys;
            if (inventory.Contains(RequiredKeyName))
            {
                // Consume key from inventory
                inventory.Remove(RequiredKeyName);
                GD.Print($"Door unlocked with key '{RequiredKeyName}' and consumed from inventory.");
                OpenDoor();
            }
            else
            {
                GD.Print($"Door is locked. Required key: '{RequiredKeyName}'.");
            }
        }
    }

    private void OpenDoor()
    {
        if (opened)
            return;

        opened = true;

        // Generated by Copilot: disable physical blocking and animate
        if (doorBody != null)
        {
            doorBody.SetPhysicsProcess(false); // turn off body processing (optional fallback)
            var doorCollisionShape = doorBody.GetNodeOrNull<CollisionShape3D>("CollisionShape3D");
            if (doorCollisionShape != null)
                doorCollisionShape.Disabled = true; // disable the actual collision shape
        }

        if (animationPlayer != null && animationPlayer.HasAnimation("Open"))
            animationPlayer.Play("Open");
        else
            Translate(new Vector3(0, 0, -3)); // simple fallback if no animation is set

        if (openEffect != null)
            openEffect.Play();

        GD.Print("Door opened.");
    }
}
