using System;
using Game.UI;
using Godot;
using GodotTask;

namespace Game.Entities;

public partial class NewBurger : RigidBody3D
{
    [Export]
    Farmer? playerToFollow;

    public Farmer? PlayerProp
    {
        get => playerToFollow;
        set { playerToFollow = value; }
    }

    [Export]
    AnimationPlayer animPlayer = null!;

    [Export]
    float maximumFollowingDistance = 5.0f;

    [Export]
    float minimumFollowingDistance = 1.0f;

    [Export]
    float followSpeed = 5.0f;

    [Export]
    float maxHealth = 100.0f;

    float currentHealth = 0.0f;

    [Export]
    StringName runAnimation = "BAKED_Walk";

    [Export]
    StringName idleAnimation = "RESET";

    [Export]
    StringName disabledAnimation = "BAKED_Activate";

    [Export]
    String disabledText = "Disabled";

    [Export]
    CollisionShape3D activatedCollisionShape = null!;

    [Export]
    CollisionShape3D disabledCollisionShape = null!;

    [Export]
    AnimationPlayer eatMePlayer = null!;

    bool disabled = false;

    // Generated by Copilot: eat/interact configuration
    [Export]
    StringName eatAction = "ui_eat";

    [Export]
    float eatRange = 2.0f;

    [Export]
    int eatAmount = 25;

    // [Export]
    // AudioStreamPlayer3D? eatFx = null!;

    [Export]
    float animationBlendAmount = 0.5f;

    [Export]
    float InvulnerabilityTime = 0.1f;

    [Export]
    public int AmountToDamagePlayer = 10;

    public override void _Ready()
    {
        currentHealth = maxHealth;
        updateHealthBar();

        // set damage meta
        DamageManager.SetMyForce(this, DamageManager.BurgerForceName);
        DamageManager.SetDamage(this, AmountToDamagePlayer);
        DamageManager.SetDamageApplyTo(this, DamageManager.FarmerForceName);
    }

    [Export]
    FancyProgressBar healthBar = null!;

    public void updateHealthBar()
    {
        // scale health to 100
        healthBar.SetCoolValue((int)(currentHealth / maxHealth * 100.0f));
        healthBar.SetLabelValue($"{currentHealth}");
    }

    public void Damage(float amount)
    {
        currentHealth -= amount;
        updateHealthBar();
        if (currentHealth <= 0.0)
            Kill();
    }

    public void Kill()
    {
        currentHealth = 0.0f;
        this.disabled = true;
        //this.RemoveMeta(EnemyMeta);
        DamageManager.ClearDamageMeta(this);
        //this.QueueFree();
    }

    //public readonly StringName EnemyMeta = "enemy";
    bool canTakeDamage = true;

    [Export]
    AudioStreamPlayer3D hurtFx = null!;

    public override void _PhysicsProcess(double delta)
    {
        // Figure out if burger is touching a bullet
        var colliding = GetCollidingBodies();
        bool touchingBullet = false;
        int amountToReduceHealth = 0;
        foreach (var collider in colliding)
        {
            //if (collider.HasMeta(EnemyMeta))
            if (DamageManager.CanDamageMe(this, collider))
            {
                touchingBullet = true;

                // Grab the amount to reduce health by
                amountToReduceHealth = DamageManager.GetDamageAmount(collider);
                //amountToReduceHealth = (int)collider.GetMeta(EnemyMeta);

                // Kill bullet
                if (collider is Bullet bullet)
                    bullet.Kill();

                break;
            }
        }

        // Take damage
        if (!disabled && canTakeDamage && touchingBullet)
        {
            // Reduce burger health
            Damage(amountToReduceHealth);

            if (!disabled)
            {
                hurtFx.Play();
                hurtPlayer.Play(hurtAnim);
                ApplyCentralForce(GlobalBasis * (Vector3.Back * knockback));
            }
            // Start invulnerability timer
            canTakeDamage = false;
            ResetInvulnerability().Forget();
        }
    }

    [Export]
    AnimationPlayer hurtPlayer = null!;

    [Export]
    StringName hurtAnim = "hurt";

    [Export]
    float knockback = 10;

    async GDTaskVoid ResetInvulnerability()
    {
        await GDTask.Delay(TimeSpan.FromSeconds(InvulnerabilityTime));
        canTakeDamage = true;
    }

    // Generated by Copilot: allow player to eat this burger when disabled
    // Heals the player and removes this node from the scene
    public void Eat()
    {
        if (playerToFollow == null)
            return;

        // Give health to the player using Farmer helper
        playerToFollow.AddHealth(eatAmount);

        // Generated by Copilot: increment burgers-eaten counter in saved game data
        Manager.Instance.Data.BurgersEaten += 1;

        // Debug for BurgersEaten count
        GD.Print(Manager.Instance.Data.BurgersEaten);

        // Play optional eat sound
        playerToFollow.EatFx?.Play();

        // Remove metadata and free the node
        //this.RemoveMeta(EnemyMeta);
        DamageManager.ClearDamageMeta(this);
        this.QueueFree();
    }

    StringName eatMeAnimName = "bounce";

    public override void _IntegrateForces(PhysicsDirectBodyState3D state)
    {
        if (disabled)
        {
            animPlayer.SpeedScale = -1.0f;
            animPlayer.Play(disabledAnimation);
            healthBar.SetLabelValue(disabledText);
            eatMePlayer.Play(eatMeAnimName);

            // apply some rotational friction
            state.AngularVelocity *= 0.9f;

            // apply some translational friction
            var horizontalVelocity = state.LinearVelocity;
            horizontalVelocity.X *= 0.95f;
            horizontalVelocity.Z *= 0.95f;
            state.LinearVelocity = horizontalVelocity;

            // drop to the ground
            activatedCollisionShape.Disabled = true;
            disabledCollisionShape.Disabled = false;

            // Allow player to press the configured action to "eat" this disabled burger
            if (playerToFollow != null)
            {
                var distToPlayer = GlobalPosition.DistanceTo(playerToFollow.GlobalPosition);
                if (distToPlayer <= eatRange && Input.IsActionJustPressed(eatAction))
                {
                    Eat();
                    return;
                }
            }

            return;
        }

        if (playerToFollow == null)
        {
            return;
        }

        animPlayer.SpeedScale = 1.0f;

        var localLinearVelocity = new Vector3();
        localLinearVelocity.X = 0;

        var myPos = GlobalPosition;
        var playerPos = playerToFollow.GlobalPosition with { Y = myPos.Y };

        this.LookAt(playerPos, Vector3.Up);

        var distanceToPlayer = myPos.DistanceTo(playerPos);

        // If close enough or too far away, do nothing
        if (
            distanceToPlayer <= minimumFollowingDistance
            || distanceToPlayer >= maximumFollowingDistance
        )
        {
            localLinearVelocity.Z = 0;
            animPlayer.Play(idleAnimation, customBlend: animationBlendAmount);
        }
        else
        {
            localLinearVelocity.Z = -followSpeed * 5;
            animPlayer.Play(runAnimation, customBlend: animationBlendAmount);
        }

        state.ApplyCentralForce(GlobalBasis * localLinearVelocity);
    }
}
