using System;
using Game;
using Godot;

namespace Game.Entities;

public partial class Pedestal : Area3D
{
    // Generated by Copilot: which statue belongs here
    [Export]
    public string RequiredStatueId { get; set; } = "statue1";

    private bool playerInZone = false;
    private bool placed = false;
    private string? placedStatueId = null;
    private Label3D? promptLabel = null;

    public override void _Ready()
    {
        BodyEntered += OnBodyEntered;
        BodyExited += OnBodyExited;
        promptLabel = GetNodeOrNull<Label3D>("Label3D");
        if (promptLabel != null)
            promptLabel.Visible = false;
    }

    private void OnBodyEntered(Node body)
    {
        if (body is Farmer)
        {
            playerInZone = true;
            if (!placed)
                GD.Print($"Pedestal ready for {RequiredStatueId}. Press [e] to place statue.");
        }
    }

    private void OnBodyExited(Node body)
    {
        if (body is Farmer)
        {
            playerInZone = false;
            if (promptLabel != null)
                promptLabel.Visible = false;
        }
    }

    public override void _PhysicsProcess(double delta)
    {
        if (promptLabel != null)
        {
            promptLabel.Visible = playerInZone;
            promptLabel.Text = placed
                ? "[e] to swap statue"
                : "[e] to place statue";
        }

        if (!playerInZone)
            return;

        if (!Input.IsActionJustPressed(GameActions.UseDoor))
            return;

        var data = Game.Manager.Instance.Data;
        var currentScene = GetTree().CurrentScene;
        Farmer? farmer = null;
        if (currentScene != null)
            farmer = currentScene.FindChild("Farmer", true, false) as Farmer;
        if (farmer == null)
            farmer = GetTree().Root.FindChild("Farmer", true, false) as Farmer;

        if (placed)
        {
            if (string.IsNullOrEmpty(data.HeldStatueId) || string.IsNullOrEmpty(placedStatueId))
                return;

            var heldStatueIdForSwap = data.HeldStatueId;
            var pedestalStatueId = placedStatueId;

            if (pedestalStatueId == RequiredStatueId)
                data.StatuePlaced[RequiredStatueId] = false;

            data.HeldStatueId = pedestalStatueId;
            placedStatueId = heldStatueIdForSwap;

            if (placedStatueId == RequiredStatueId)
                data.StatuePlaced[RequiredStatueId] = true;

            foreach (var child in GetChildren())
            {
                if (child is Statue statueChild)
                    statueChild.QueueFree();
            }

            var statueSceneSwap = GD.Load<PackedScene>("res://Scenes/Entities/Statue.tscn");
            if (statueSceneSwap != null)
            {
                var swappedStatue = statueSceneSwap.Instantiate<Statue>();
                swappedStatue.StatueId = placedStatueId;
                AddChild(swappedStatue);
                swappedStatue.Position = new Vector3(0, 0.5f, 0);
            }

            farmer?.DisplayHeldStatue(data.HeldStatueId, null);

            if (currentScene != null)
            {
                var statueDoors = new System.Collections.Generic.List<StatueDoor>();
                CollectStatueDoors(currentScene, statueDoors);
                foreach (var statueDoor in statueDoors)
                    statueDoor.OpenIfStatuesPlaced();
            }
            return;
        }

        if (string.IsNullOrEmpty(data.HeldStatueId))
        {
            GD.Print("You are not holding a statue to place.");
            return;
        }

        // Place currently held statue (correct or incorrect pedestal).
        var heldStatueId = data.HeldStatueId;
        placed = true;
        placedStatueId = heldStatueId;
        data.HeldStatueId = null;

        bool correctPlacement = heldStatueId == RequiredStatueId;
        if (correctPlacement)
        {
            data.StatuePlaced[RequiredStatueId] = true;
            GD.Print($"Placed statue '{heldStatueId}' on correct pedestal. ({RequiredStatueId} done.)");
        }
        else
        {
            GD.Print(
                $"Placed statue '{heldStatueId}' on wrong pedestal. Needs '{RequiredStatueId}' here."
            );
        }

        // Generated by Copilot: clear hand display when statue is placed
        if (farmer != null)
        {
            farmer.ClearHeldStatueDisplay();
        }

        // Generated by Copilot: check all statue doors to see if they should open
        if (currentScene != null)
        {
            // Generated by Copilot: recursively find all StatueDoor nodes
            var statueDoors = new System.Collections.Generic.List<StatueDoor>();
            CollectStatueDoors(currentScene, statueDoors);

            GD.Print($"[Pedestal] Found {statueDoors.Count} statue doors to check");
            foreach (var statueDoor in statueDoors)
            {
                GD.Print($"[Pedestal] Calling OpenIfStatuesPlaced on statue door");
                statueDoor.OpenIfStatuesPlaced();
            }
        }

        // Generated by Copilot: instantiate and display the statue that was placed
        var statueScene = GD.Load<PackedScene>("res://Scenes/Entities/Statue.tscn");
        if (statueScene != null)
        {
            var placedStatueInstance = statueScene.Instantiate<Statue>();
            placedStatueInstance.StatueId = heldStatueId;
            AddChild(placedStatueInstance);
            placedStatueInstance.Position = new Vector3(0, 0.5f, 0); // Offset to show on pedestal
        }
    }

    // Allow re-placing if the statue gets picked back up from this pedestal.
    public void OnStatuePickedUp(string statueId)
    {
        if (!placed || placedStatueId != statueId)
            return;

        if (placedStatueId == RequiredStatueId)
            Game.Manager.Instance.Data.StatuePlaced[RequiredStatueId] = false;

        placed = false;
        placedStatueId = null;
    }

    // Generated by Copilot: helper method to recursively find all StatueDoor nodes in the scene tree
    private static void CollectStatueDoors(
        Node node,
        System.Collections.Generic.List<StatueDoor> doors
    )
    {
        if (node is StatueDoor statueDoor)
        {
            doors.Add(statueDoor);
        }

        foreach (Node child in node.GetChildren())
        {
            CollectStatueDoors(child, doors);
        }
    }
}
