using System;
using Game.Entities;
using Godot;

namespace Game.Entities;

public partial class StatueDoor : Node3D
{
    // Generated by Copilot: door info for color/identification
    [Export]
    public DoorInfo Info { get; set; } = null!;

    // Generated by Copilot: mesh and animation
    [Export]
    private CsgBox3D DoorMesh = null!;

    [Export]
    private AnimationPlayer animPlayer = null!;

    [Export]
    private StringName OpenAnimName = "open";

    // Generated by Copilot: track if door has been opened
    public bool Opened { get; set; } = false;

    public override void _Ready()
    {
        // Generated by Copilot: apply door color from info if both are assigned
        if (DoorMesh != null && Info != null)
        {
            var mat = (StandardMaterial3D)this.DoorMesh.Material;
            if (mat != null)
            {
                mat.AlbedoColor = Info.DoorColor;
            }
        }
        else
        {
            GD.PrintErr("[StatueDoor] DoorMesh or Info not assigned in scene editor!");
        }
    }

    // Generated by Copilot: check if all 4 statues are placed and open door if true
    public void OpenIfStatuesPlaced()
    {
        if (Opened)
        {
            GD.Print("[StatueDoor] Door already opened");
            return;
        }

        if (animPlayer == null)
        {
            GD.PrintErr("[StatueDoor] AnimationPlayer not assigned!");
            return;
        }

        var data = Game.Manager.Instance.Data;

        // Generated by Copilot: verify all 4 statues are placed
        bool statue1Placed =
            data.StatuePlaced.ContainsKey("statue1") && data.StatuePlaced["statue1"];
        bool statue2Placed =
            data.StatuePlaced.ContainsKey("statue2") && data.StatuePlaced["statue2"];
        bool statue3Placed =
            data.StatuePlaced.ContainsKey("statue3") && data.StatuePlaced["statue3"];
        bool statue4Placed =
            data.StatuePlaced.ContainsKey("statue4") && data.StatuePlaced["statue4"];

        GD.Print(
            $"[StatueDoor] Checking statues: 1={statue1Placed}, 2={statue2Placed}, 3={statue3Placed}, 4={statue4Placed}"
        );

        bool allStatuesPlaced = statue1Placed && statue2Placed && statue3Placed && statue4Placed;

        if (allStatuesPlaced)
        {
            animPlayer.Play(OpenAnimName);
            Opened = true;
            GD.Print("[StatueDoor] All statues placed! Door opens!");
        }
    }
}
