// Generated by Github Copilot
using System;
using Game;
using Godot;
using GodotTask;

namespace Game.Entities;

public partial class Gun : Node3D
{
    [Export]
    Node3D bulletSpawnPoint = null!;

    [Export]
    PackedScene bulletScene = null!;

    [Export]
    float bulletSpeed = 80.0f;

    [Export]
    float despawnTime = 15.0f;

    [Export]
    float reloadTime = 0.15f;

    bool readyToFire = true;

    [Export]
    AudioStreamPlayer? shootfx;

    public override void _Ready()
    {
        // Nothing to do on ready for now.
    }

    public override void _Process(double delta)
    {
        // if (Input.IsActionPressed(GameActions.PlayerFire) && readyToFire)
        // {
        //     var newBullet = bulletScene.Instantiate<RigidBody3D>();
        //     ((Bullet)newBullet).SetDamageAmount(5).SetDamageAppliesTo(DamageManager.BurgerForceName);

        //     newBullet.GlobalTransform = bulletSpawnPoint.GlobalTransform;
        //     newBullet.LinearVelocity =
        //         bulletSpawnPoint.GlobalBasis * new Vector3(bulletSpeed, 0, 0);

        //     GetTree().CurrentScene.AddChild(newBullet);
        //     shootfx?.Play();

        //     // Remove the bullet after some time
        //     var timer = GetTree().CreateTimer(despawnTime);
        //     timer.Timeout += newBullet.QueueFree;

        //     readyToFire = false;
        //     StartReload();
        // }
    }

    async void StartReload()
    {
        await GDTask.Delay(TimeSpan.FromSeconds(reloadTime));
        readyToFire = true;
    }
}
