using System;
using Game.Entities;
using Godot;

[GlobalClass]
public partial class Keys : Area3D
{
    [Export]
    public Item Info { get; set; } = new();

    [Export]
    AnimationPlayer player = null!;

    [Export]
    Sprite3D mesh = null!;

    [Export]
    StringName spinAnim = "spin";

    // Called when the node enters the scene tree for the first time.
    public override void _Ready()
    {
        mesh.Texture = Info.Icon;
        BodyEntered += OnBodyEntered;
        player.Play(spinAnim);
    }

    //Generated by Copilot
    private void OnBodyEntered(Node body)
    {
        if (body is Farmer farmer)
        {
            // Add the key to inventory (using its ID)
            //Game.Manager.Instance.Data.CollectedKeys.Add(Info.LockID);
            //Game.Manager.Instance.InventoryInstance.AddItem(resource);
            farmer.inventory.AddItem(Info);
            GD.Print($"[Keys] - Picked up key: {Info.Name}");
            //GD.Print($"Picked up key: {Game.Manager.Instance.Data.CollectedKeys}");

            // Despawn the key
            QueueFree();
        }
    }
}
