using System;
using Game;
using Godot;

namespace Game.Entities;

public partial class Statue : Area3D
{
    // Generated by Copilot: unique statue identifier
    [Export]
    public string StatueId { get; set; } = "statue1";

    private bool playerInZone = false;
    private MeshInstance3D? meshInstance = null;
    private Label3D? promptLabel = null;

    public override void _Ready()
    {
        // Generated by Copilot: connect area signals
        BodyEntered += OnBodyEntered;
        BodyExited += OnBodyExited;

        // Apply visual differentiation based on statue ID
        ApplyStatueVisuals(); // Added by copilot

        promptLabel = GetNodeOrNull<Label3D>("Label3D");
        if (promptLabel != null)
            promptLabel.Visible = false;
    }

    // Generated by Copilot: apply unique color to each statue
    private void ApplyStatueVisuals()
    {
        meshInstance = GetNode<MeshInstance3D>("MeshInstance3D");
        if (meshInstance == null)
            return;

        var material = new StandardMaterial3D();
        material.AlbedoColor = StatueId switch
        {
            "statue1" => new Color(0.8f, 0.7f, 0.5f, 1f),  // Gold/tan
            "statue2" => new Color(0.6f, 0.6f, 0.6f, 1f),  // Silver/gray
            "statue3" => new Color(0.2f, 0.2f, 0.2f, 1f),  // Dark/bronze
            "statue4" => new Color(0.4f, 0.5f, 0.6f, 1f),  // Blue-tinted marble
            _ => new Color(0.5f, 0.4f, 0.3f, 1f),          // Default brown
        };
        meshInstance.SetSurfaceOverrideMaterial(0, material);
    }

    private void OnBodyEntered(Node body)
    {
        if (body is Farmer)
        {
            playerInZone = true;
            if (promptLabel != null)
            {
                promptLabel.Text = "[e] to pick up statue";
                promptLabel.Visible = true;
            }
        }
    }

    private void OnBodyExited(Node body)
    {
        if (body is Farmer)
        {
            playerInZone = false;
            if (promptLabel != null)
                promptLabel.Visible = false;
        }
    }

    public override void _PhysicsProcess(double delta)
    {
        if (!playerInZone)
            return;

        if (!Input.IsActionJustPressed(GameActions.UseDoor))
            return;

        // Generated by Copilot: enforce one statue max carried
        var data = Game.Manager.Instance.Data;
        if (!string.IsNullOrEmpty(data.HeldStatueId))
        {
            GD.Print($"Already carrying statue '{data.HeldStatueId}'. Place it first.");
            return;
        }

        data.HeldStatueId = StatueId;
        GD.Print($"Picked up statue '{StatueId}'.");

        if (GetParent() is Pedestal pedestal)
            pedestal.OnStatuePickedUp(StatueId);

        // Generated by Copilot: remove statue from world and disable collisions
        Visible = false;
        SetProcess(false);
        SetPhysicsProcess(false);

        if (promptLabel != null)
            promptLabel.Visible = false;

        var shape = GetNodeOrNull<CollisionShape3D>("CollisionShape3D");
        if (shape != null)
            shape.Disabled = true;

        // Update the hand display on the player
        UpdatePlayerHandDisplay();
    }

    // Generated by Copilot: update hand display when statue is picked up
    private void UpdatePlayerHandDisplay()
    {
        // Find the Farmer (player) by searching from the current scene
        var currentScene = GetTree().CurrentScene;
        Farmer? farmer = null;

        if (currentScene != null)
        {
            farmer = currentScene.FindChild("Farmer", true, false) as Farmer;
        }

        // Fallback: search from root if current scene didn't work
        if (farmer == null)
        {
            GD.Print("[Statue] Farmer not found in current scene, searching from root...");
            var root = GetTree().Root;
            farmer = root.FindChild("Farmer", true, false) as Farmer;
        }

        if (farmer != null)
        {
            GD.Print($"[Statue] Found Farmer, calling DisplayHeldStatue for {StatueId}");
            farmer.DisplayHeldStatue(StatueId, meshInstance?.GetActiveMaterial(0) as StandardMaterial3D);
        }
        else
        {
            GD.PrintErr("[Statue] Could not find Farmer in scene!");
        }
    }
}
